/** Ana sidebar — sadeleştirilmiş menü (hub yapısı) */
export const MAIN_NAV = [
  { id: 'enterprise-ceo-dashboard', label: 'CEO Dashboard' },
  { id: 'dashboard', label: 'Dashboard' },
  { id: 'executive-center', label: 'Yönetici Merkezi' },
  { id: 'executive-command-center', label: 'CEO Komuta Merkezi', indent: true },
  { id: 'ceo-copilot', label: 'CEO Copilot', indent: true },
  { id: 'enterprise-release', label: 'Enterprise 1.0', indent: true },
  { id: 'digital-workforce', label: 'Digital Workforce' },
  { id: 'operation-center', label: 'Operasyon Rehberi' },
  { id: 'operation-automation-center', label: 'Operasyon Otomasyon Merkezi' },
  { id: 'pilot-readiness', label: 'Pilot Hazırlık' },
  { id: 'go-live', label: 'GO LIVE' },
  { id: 'system-health', label: 'System Health' },
  { id: 'error-center', label: 'Error Center' },
  { id: 'orders', label: 'Siparişler' },
  { id: 'shipment-ops', label: 'Sevk Operasyonu' },
  { id: 'supply-incoming', label: 'Tedarik & Gelen Ürün' },
  { id: 'collection', label: 'Tahsilat' },
  { id: 'ssh-service', label: 'SSH / Servis Merkezi' },
  { id: 'operation-cases', label: 'Operasyon Merkezi' },
  { id: 'operation-map', label: 'Operasyon Haritası', indent: true },
  { id: 'product-master-center', label: 'Ürün Master Merkezi' },
  { id: 'product-health', label: 'Ürün Sağlık Merkezi' },
  { id: 'product-publish-readiness', label: 'Yayına Hazır Merkezi' },
  { id: 'commerce-publishing', label: 'EVTREND Yayın Merkezi' },
  { id: 'ceo-control-center', label: 'CEO Kontrol Merkezi' },
  { id: 'manager-cockpit', label: 'Yönetici Kokpiti' },
  { id: 'profitability-analytics', label: 'Kârlılık Analitiği' },
  { id: 'sales-source-analytics', label: 'Satış Kaynağı Analitiği' },
  { id: 'business-rules', label: 'İş Kuralları Merkezi' },
  { id: 'data-quality', label: 'Veri Kalitesi Merkezi' },
  { id: 'users-admin', label: 'Kullanıcılar' },
]

export const PAGE_TITLE = {
  'enterprise-ceo-dashboard': 'CEO Dashboard',
  'enterprise-release': 'Enterprise 1.0 Release',
  dashboard: 'Dashboard',
  'operation-map': 'Operasyon Haritası',
  'executive-center': 'Yönetici Merkezi',
  'executive-command-center': 'CEO Komuta Merkezi',
  'ceo-copilot': 'CEO Copilot',
  'digital-workforce': 'Digital Workforce',
  'operation-center': 'Operasyon Rehberi',
  'operation-automation-center': 'Operasyon Otomasyon Merkezi',
  'pilot-readiness': 'Pilot Hazırlık',
  'go-live': 'GO LIVE',
  'system-health': 'System Health',
  'error-center': 'Error Center',
  orders: 'Siparişler',
  'shipment-ops': 'Sevk Operasyonu',
  shipment: 'Sevk Operasyonu',
  'shipment-calendar': 'Sevk Operasyonu',
  'supply-incoming': 'Tedarik & Gelen Ürün',
  collection: 'Tahsilat',
  'ssh-service': 'SSH / Servis Merkezi',
  'operation-cases': 'Operasyon Merkezi',
  'product-master-center': 'Ürün Master Merkezi',
  'product-health': 'Ürün Sağlık Merkezi',
  'product-publish-readiness': 'Yayına Hazır Merkezi',
  'commerce-publishing': 'EVTREND Yayın Merkezi',
  'ceo-control-center': 'CEO Kontrol Merkezi',
  'manager-cockpit': 'Yönetici Kokpiti',
  'profitability-analytics': 'Kârlılık Analitiği',
  'sales-source-analytics': 'Satış Kaynağı Analitiği',
  'business-rules': 'İş Kuralları Merkezi',
  'business-rule-tester': 'Rule Tester',
  'data-quality': 'Veri Kalitesi Merkezi',
  'users-admin': 'Kullanıcı Yönetimi',
  products: 'Ürün Kartları',
  'media-center': 'Medya Merkezi',
  'woocommerce-connector': 'WooCommerce Connector',
  'executive-war-room': 'Yönetim Savaş Odası',
  'cash-radar': 'Nakit Radarı',
  'automation-center': 'Operasyon Otomasyonu',
  'action-center': 'Otomatik Aksiyon Merkezi',
  'operations-agents': 'Otonom Operasyon Ajanları',
  'executive-director': 'AI Operasyon Direktörü',
  'strategic-intelligence': 'Stratejik Karar Merkezi',
  'company-simulation': 'Otonom Şirket Simülasyonu',
  'board-directors': 'Otonom Yönetim Kurulu',
  'ceo-intelligence': 'Otonom CEO',
  'chairman-intelligence': 'Otonom Şirket Başkanı',
  'future-engine': 'Kurumsal Gelecek Motoru',
  'investor-intelligence': 'Yatırımcı Merkezi',
  'holding-center': 'Holding Yönetim Merkezi',
  'group-chairman': 'Otonom Holding Başkanı',
  'business-brain': 'Otonom İşletme Beyni',
  'action-orchestrator': 'Otonom Aksiyon Orkestratörü',
  'performance-feedback': 'Otonom Performans Takip Motoru',
  'learning-engine': 'Kurumsal Öğrenme Motoru',
  'optimization-engine': 'Otonom Optimizasyon Motoru',
  'goal-engine': 'Otonom Hedef Motoru',
  'enterprise-command-center': 'Kurumsal Kumanda Merkezi',
  'forecast-engine': 'Tahmin Motoru',
  'ai-operations-advisor': 'AI Operasyon Danışmanı',
}

/** Eski rota id → birleşik sevk operasyonu */
export const LEGACY_SHIPMENT_PAGE_IDS = new Set(['shipment', 'shipment-calendar'])

/**
 * @param {string} pageId
 */
export function normalizePageId(pageId) {
  if (LEGACY_SHIPMENT_PAGE_IDS.has(pageId)) return 'shipment-ops'
  return pageId
}
