/**
 * Domain event type stringleri (wire).
 * @typedef {'payment.posted' | 'payment.pending' | 'shipment.dispatched' | 'shipment.partial' | 'shipment.planned' | 'shipment.loaded' | 'shipment.delivered' | 'installation.completed' | 'installation.issue' | 'risk.escalated' | 'order.lifecycle_changed' | 'order_line.committed_ship_by_changed' | 'order.placed' | 'delivery.failed' | 'delivery.completed' | 'task.created' | 'task.completed' | 'missing_item.created' | 'missing_item.ordered' | 'missing_item.arrived' | 'missing_item.ready_for_shipment' | 'missing_item.resolved'} DomainEventTypeWire
 */

export const DOMAIN_EVENT_TYPE = /** @type {const} */ ({
  PAYMENT_POSTED: 'payment.posted',
  PAYMENT_PENDING: 'payment.pending',
  PAYMENT_APPROVED: 'payment.approved',
  PAYMENT_REJECTED: 'payment.rejected',
  SHIPMENT_DISPATCHED: 'shipment.dispatched',
  SHIPMENT_PARTIAL: 'shipment.partial',
  SHIPMENT_PLANNED: 'shipment.planned',
  SHIPMENT_LOADED: 'shipment.loaded',
  SHIPMENT_DELIVERED: 'shipment.delivered',
  INSTALLATION_COMPLETED: 'installation.completed',
  INSTALLATION_ISSUE: 'installation.issue',
  RISK_ESCALATED: 'risk.escalated',
  ORDER_LIFECYCLE_CHANGED: 'order.lifecycle_changed',
  ORDER_LINE_COMMITTED_SHIP_BY_CHANGED: 'order_line.committed_ship_by_changed',
  ORDER_PLACED: 'order.placed',
  DELIVERY_FAILED: 'delivery.failed',
  DELIVERY_COMPLETED: 'delivery.completed',
  TASK_CREATED: 'task.created',
  TASK_COMPLETED: 'task.completed',
  AI_SALES_TASK_CREATED: 'ai_sales.task.created',
  AI_SALES_TASK_COMPLETED: 'ai_sales.task.completed',
  AI_SALES_CALL_LOGGED: 'sales.follow_up.call_logged',
  AI_COLLECTION_TASK_CREATED: 'ai.collection.task.created',
  AI_COLLECTION_TASK_COMPLETED: 'ai.collection.task.completed',
  AI_SHIPMENT_TASK_CREATED: 'ai.shipment.task.created',
  AI_SHIPMENT_TASK_COMPLETED: 'ai.shipment.task.completed',
  AI_PROCUREMENT_TASK_CREATED: 'ai.procurement.task.created',
  AI_PROCUREMENT_TASK_COMPLETED: 'ai.procurement.task.completed',
  AI_ORCHESTRATION_CHAIN_COMPLETED: 'ai.orchestration.chain.completed',
  MISSING_ITEM_CREATED: 'missing_item.created',
  MISSING_ITEM_ORDERED: 'missing_item.ordered',
  MISSING_ITEM_ARRIVED: 'missing_item.arrived',
  MISSING_ITEM_READY_FOR_SHIPMENT: 'missing_item.ready_for_shipment',
  MISSING_ITEM_RESOLVED: 'missing_item.resolved',
  SALES_CONTRACT_PRINTED: 'sales.contract_printed',
  POLICY_OVERRIDE: 'policy.override',
  SHIPMENT_PLAN_CREATED: 'shipment.plan.created',
  SHIPMENT_PLAN_UPDATED: 'shipment.plan.updated',
  SHIPMENT_GROUP_CREATED: 'shipment.group.created',
  SHIPMENT_GROUP_APPLIED: 'shipment.group.applied',
  SHIPMENT_DISPATCH_SHEET_PRINTED: 'shipment.dispatch_sheet_printed',
  DISPATCH_ADVICE_GENERATED: 'dispatch.advice.generated',
  DISPATCH_AUTO_PLANNED: 'dispatch.auto_planned',
  DISPATCH_RISK_DETECTED: 'dispatch.risk_detected',
  DELIVERY_CONFIRMATION_REQUIRED: 'delivery.confirmation.required',
  DELIVERY_CONFIRMED: 'delivery.confirmed',
  DELIVERY_POSTPONED: 'delivery.postponed',
  DELIVERY_REVERTED: 'delivery.reverted',
  SUPPLY_ORDER_SENT: 'supply.order.sent',
  SUPPLY_ORDER_REVERTED: 'supply.order.reverted',
  INCOMING_GOODS_RECORDED: 'incoming_goods.recorded',
  SUPPLIER_LEDGER_ENTRY: 'supplier_ledger.entry',
  PRODUCT_MASTER_UPDATED: 'product.updated',
  AI_TOOL_REQUESTED: 'ai.tool.requested',
  AI_TOOL_EXECUTED: 'ai.tool.executed',
  AI_TOOL_FAILED: 'ai.tool.failed',
  AI_TOOL_WAITING_APPROVAL: 'ai.tool.waiting_approval',
  AI_TOOL_APPROVED: 'ai.tool.approved',
  AI_TOOL_REJECTED: 'ai.tool.rejected',
  AI_TOOL_DENIED: 'ai.tool.denied',
  AI_COMPANY_MANAGER_DECISION: 'ai.company_manager.decision',
  AI_COMPANY_MANAGER_SCAN: 'ai.company_manager.scan',
  AI_COMPANY_BRAIN_DECISION: 'ai.company_brain.decision',
  AI_COMPANY_BRAIN_SCAN: 'ai.company_brain.scan',
})
