/** FAZ 103 — Company Knowledge Graph (client contracts). */

export const GRAPH_NODE_TYPE = {
  CUSTOMER: 'Customer',
  ORDER: 'Order',
  PRODUCT: 'Product',
  SUPPLIER: 'Supplier',
  PAYMENT: 'Payment',
  SHIPMENT: 'Shipment',
  WORKER: 'Worker',
  EMPLOYEE: 'Employee',
  TASK: 'Task',
  RISK: 'Risk',
  AI_WORKER: 'AIWorker',
}

export const GRAPH_EDGE_TYPE = {
  CUSTOMER_HAS_ORDER: 'CUSTOMER_HAS_ORDER',
  ORDER_HAS_PRODUCT: 'ORDER_HAS_PRODUCT',
  ORDER_HAS_PAYMENT: 'ORDER_HAS_PAYMENT',
  ORDER_HAS_SHIPMENT: 'ORDER_HAS_SHIPMENT',
  SHIPMENT_ASSIGNED_TO: 'SHIPMENT_ASSIGNED_TO',
  PAYMENT_BELONGS_TO: 'PAYMENT_BELONGS_TO',
  SUPPLIER_SUPPLIES_PRODUCT: 'SUPPLIER_SUPPLIES_PRODUCT',
  EMPLOYEE_HAS_ORDER: 'EMPLOYEE_HAS_ORDER',
  WORKER_CREATED_TASK: 'WORKER_CREATED_TASK',
  TASK_CREATED_RISK: 'TASK_CREATED_RISK',
  AI_SOLVED_RISK: 'AI_SOLVED_RISK',
  WORKER_COLLABORATES_WITH: 'WORKER_COLLABORATES_WITH',
}

export const GRAPH_QUERY = {
  OVERDUE_PAYMENT_READY_SHIPMENT: 'overdue_payment_ready_shipment',
  EMPLOYEE_RISKY_CUSTOMERS: 'employee_risky_customers',
}
